app = "gitcoin-search-dev"
primary_region = "den"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  DEPLOYMENT_ENVIRONMENT = "production"
  PORT = "8000"
  STORAGE_DIR = "/tmp/data"
  APPLICATION_FILES_LOCATORS = "42161:26,42161:27,42161:25,42161:23,42161:29,42161:24,10:9,42161:31,42161:28"
  BIND_ADDRESS = "0.0.0.0"
  HTTP_WORKERS = "4"
  ANONYMIZED_TELEMETRY = "False"
  INDEXER_BASE_URL = "https://grants-stack-indexer.gitcoin.co"
  LOG_LEVEL = "DEBUG"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
    
  [[services.http_checks]]
    grace_period = "30s"
    interval = "30s"
    path = "/health"
    timeout = "10s"
    method = "get"
    protocol = "http"
